---
settings:
  name: Release notes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    auto_release_notes_enabled: true
    repositories_features:
    - workload-fsx-ontap
    - 
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 작업 부하 공장 릴리스 노트
    url: "/index.html"
  - title: 최근 변경 사항
    url: "/whats-new.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: Workload Factory
  repo: workload-family
