---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: BlueXP  워크로드 팩토리에 포함된 워크로드의 최근 변경사항에 대해 알아보십시오. 
---
= BlueXP  워크로드 팩토리의 최근 변경사항
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 팩토리에 포함된 워크로드의 최근 변경사항에 대해 알아보십시오.



== 2025년 06월 29일



=== VMware 워크로드



==== Amazon Elastic VMWare Service에 대한 마이그레이션 어드바이저 지원 소개

VMware용 BlueXP 워크로드 팩토리가 이제 Amazon Elastic VMware Service를 지원합니다. 마이그레이션 어드바이저를 사용하여 온프레미스 VMware 워크로드를 Amazon Elastic VMware Service로 신속하게 마이그레이션하여 비용을 최적화하고 애플리케이션을 리팩토링하거나 플랫폼을 재구축할 필요 없이 VMware 환경을 더욱 효과적으로 제어할 수 있습니다.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["마이그레이션 어드바이저를 사용하여 Amazon EVS에 대한 배포 계획을 만듭니다."]



=== GenAI 워크로드



==== 일반 NFS/SMB 파일 시스템에 호스팅된 데이터 소스 지원

이제 일반 SMB 또는 NFS 공유에서 데이터 소스를 추가할 수 있습니다. 이를 통해 Amazon FSx for NetApp ONTAP 이외의 파일 시스템에서 호스팅되는 볼륨에 저장된 파일을 포함할 수 있습니다.

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["지식 기반에 데이터 소스 추가"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["커넥터에 데이터 소스 추가"]



== 2025년 06월 16일



=== 빌더 작업량



==== 클론 지원

이제 Builders용 BlueXP 워크로드 팩토리에서 프로젝트를 복제할 수 있습니다. 프로젝트를 복제하면 Builders는 스냅샷에서 원본과 동일한 구성으로 새 프로젝트를 생성합니다. 복제는 유사한 프로젝트를 빠르게 생성하거나 테스트 목적으로 사용할 때 유용합니다. Builders의 지침에 따라 새 프로젝트 복제본을 마운트할 수 있습니다.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Builders 프로젝트를 위한 BlueXP 워크로드 팩토리 버전 관리"]



== 2025년 06월 08일



=== NetApp ONTAP용 Amazon FSx



==== 문제 해결을 위한 새로운 잘 설계된 분석 및 지원

FSx for ONTAP 파일 시스템에 대한 자동 용량 관리가 이제 잘 설계된 상태 대시보드의 구성 분석으로 포함되었습니다.

또한, 워크로드 팩토리는 이제 다음과 같은 구성 문제를 해결하는 기능을 지원합니다.

* SSD 용량 임계값입니다
* 데이터 계층화
* 예약된 로컬 스냅샷
* ONTAP 백업을 위한 FSx
* 원격 데이터 복제
* 스토리지 효율성
* 자동 용량 관리


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["구성 문제 해결"]



== 2025년 06월 03일



=== NetApp ONTAP용 Amazon FSx



==== 볼륨 자동 증가 향상

이제 볼륨의 자동 증가 크기를 설정하여 볼륨 크기가 비즈니스 요구 사항과 애플리케이션 요구 사항에 맞게 프로비저닝된 크기를 넘어 증가할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["볼륨 자동 확장 활성화"]



==== 잘 설계된 분석 업데이트

이제 Workload Factory가 FSx for ONTAP 파일 시스템을 분석하여 데이터 압축, 중복 제거를 포함한 스토리지 효율성이 활용되고 있는지 확인합니다. 스토리지 효율성은 파일 시스템이 사용 가능한 공간을 얼마나 효율적으로 사용하는지 측정합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["잘 설계된 저장 효율성 상태를 확인하세요"]



==== 스토리지 대시보드 개선

오늘부터 워크로드 팩토리 콘솔에서 스토리지 워크로드를 열면 *대시보드*가 표시됩니다. 새롭게 디자인된 대시보드는 파일 시스템 수, 총 SSD 용량, 잘 설계된 상태 개요, 데이터 보호 개요, 복제 관계 상태 등 FSx for ONTAP 시스템에 대한 전체적인 정보를 제공합니다.



==== 볼륨 탭 개선

스토리지 워크로드는 워크로드 팩토리 콘솔의 FSx for ONTAP 파일 시스템 내 볼륨 탭을 개선했습니다. 개선된 기능은 다음과 같습니다.

* *새로운 카드*: SSD 용량, 용량 풀 및 자율 랜섬웨어 보호(ARP)
* *새로운 열*: 용량 분배, 사용된 SSD 용량, 사용된 용량 풀 및 SSD 효율성




==== 볼륨 생성을 위한 스토리지 효율성 업데이트

새 볼륨을 생성할 때 데이터 압축, 압축, 중복 제거를 포함한 스토리지 효율성이 기본적으로 활성화됩니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["워크로드 팩토리에서 새 볼륨을 만듭니다."]



=== 데이터베이스 워크로드



==== PostgreSQL 및 Oracle 감지

이제 워크로드 팩토리 콘솔에서 AWS 계정에서 PostgreSQL 서버 데이터베이스와 Oracle 데이터베이스 배포를 실행하는 인스턴스를 검색할 수 있습니다. 검색된 인스턴스는 데이터베이스 인벤토리에 표시됩니다.



==== 업데이트된 "최적화" 용어

이전에는 "최적화"라고 불렸던 워크로드 팩토리는 이제 "잘 설계된 문제"와 "잘 설계된 상태"를 사용하여 데이터베이스 구성 분석을 설명하고 "수정"을 사용하여 모범 사례 권장 사항을 충족하도록 데이터베이스 구성을 개선할 수 있는 기회를 수정하는 방법을 설명합니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["워크로드 팩토리의 데이터베이스 환경에 대한 구성 분석"]



==== 호스트 인스턴스에 대한 향상된 온보딩

호스트 인스턴스 관리에 "감지되지 않음", "관리되지 않음" 또는 "관리됨"이라는 용어를 사용하는 대신, 이제 워크로드 팩토리는 호스트 인스턴스 온보딩에 "등록"을 사용합니다. 새로운 등록 프로세스에는 호스트 인스턴스 인증 및 준비가 포함되어 워크로드 팩토리 콘솔에서 데이터베이스 구성의 리소스를 생성, 모니터링, 분석 및 수정할 수 있습니다. 등록 프로세스의 준비 단계는 호스트 인스턴스가 관리할 준비가 되었는지 여부를 나타냅니다.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["인스턴스 관리"]



=== GenAI 워크로드



==== 추적기를 사용하여 작업을 모니터링하고 추적할 수 있습니다

GenAI에서 Tracker 모니터링 기능을 사용할 수 있습니다. Tracker를 사용하면 보류 중, 진행 중 및 완료된 작업의 진행 상황과 상태를 모니터링 및 추적하고, 작업 및 하위 작업의 세부 정보를 검토하고, 문제나 오류를 진단하고, 실패한 작업의 매개변수를 편집하고, 실패한 작업을 다시 시도할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["BlueXP 워크로드 팩토리의 Tracker를 사용하여 워크로드 작업을 모니터링합니다."]



==== 지식 기반에 대한 재순위 모델을 선택하세요

이제 지식 기반에 사용할 특정 리랭커 모델을 선택하여 리랭킹된 쿼리 결과의 관련성을 높일 수 있습니다. GenAI는 Cohere Rerank 및 Amazon Rerank 모델을 지원합니다.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["GenAI 기술 자료를 만듭니다"]



== 2025년 05월 04일



=== NetApp ONTAP용 Amazon FSx



==== FSx for ONTAP 파일 시스템에 대한 자율적인 랜섬웨어 방어

NAS(NFS/SMB) 환경에서 워크로드 분석을 사용하여 랜섬웨어 공격으로 이어질 수 있는 비정상적인 활동을 감지하여 경고하는 기능인 ARP(자율적 랜섬웨어 방어)로 데이터를 보호합니다. 공격이 의심되면 ARP는 데이터를 복원할 수 있는 변경 불가능한 새로운 스냅샷을 만듭니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["자율적 랜섬웨어 방어 기능으로 데이터를 보호하십시오"]



==== FlexGroup 볼륨 재조정 개선 사항

BlueXP  워크로드 팩토리에서는 FlexGroup 볼륨의 데이터 균형을 재조정하는 다양한 레이아웃 옵션이 포함된 FlexGroup 볼륨 재조정 마법사를 소개합니다. 재조정은 데이터를 FlexGroup 구성원 볼륨에 균등하게 재분배합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["FlexGroup 볼륨에서 용량을 재조정합니다"]



==== FSx for ONTAP 파일 시스템에 대한 모범 사례 구현

BlueXP  워크로드 팩토리에서는 파일 시스템 구성의 체계적으로 상태를 검토할 수 있는 대시보드를 제공합니다. 이 분석을 활용하여 FSx for ONTAP 파일 시스템에 대한 모범 사례를 구현할 수 있습니다. 파일 시스템 구성 분석에는 SSD 용량 임계값, 예약된 로컬 스냅샷, 예약된 FSx for ONTAP 백업, 데이터 계층화, 원격 데이터 복제 구성이 포함됩니다.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["파일 시스템 구성을 위한 잘 설계된 분석에 대해 알아보십시오"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["파일 시스템에 대한 모범 사례 구현"]




==== 이중 프로토콜 볼륨 보안 스타일 옵션

NTFS 또는 UNIX를 볼륨의 보안 스타일로 선택하여 사용자와 권한이 볼륨에 액세스하는 방법을 결정할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["볼륨을 생성합니다"]



==== 향상된 복제 기능



===== FSx for ONTAP에서 온프레미스로 역복제가 지원됩니다

이제 워크로드 공장 콘솔 내에서 FSx for ONTAP 파일 시스템에서 온프레미스 ONTAP 클러스터로 역방향 복제를 사용할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["역방향 복제"]



===== 데이터 보호 볼륨 복제

이제 데이터 보호 볼륨을 복제할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["데이터 보호 볼륨을 복제합니다"]



===== 다중 볼륨 선택

여러 볼륨을 선택할 수 있으므로 복제할 볼륨을 정확히 선택할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["복제 관계를 생성합니다"]



===== 장기 보존 정책 레이블

복제 관계에 대해 장기 보존을 설정하는 경우 소스 및 타겟 볼륨 레이블이 정확히 일치해야 합니다. 이제 BlueXP  워크로드 팩토리에서 누락된 소스 볼륨 레이블을 자동으로 생성할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["복제 관계를 생성합니다"]



==== FSx for ONTAP 파일 이름이 볼륨 생성 시 표시됩니다

볼륨 생성 중에 FSx for ONTAP 파일 시스템의 가시성을 개선했습니다. 볼륨을 생성할 때 FSx for ONTAP 파일 시스템을 보게 되므로 볼륨이 생성되는 위치를 정확하게 알 수 있습니다.



==== 스토리지 워크로드 전체에 AWS 계정이 표시됩니다

스토리지 작업 부하에서 계정 가시성이 개선되었습니다. 볼륨 *, * 스토리지 VM * 및 * 복제 * 탭으로 이동하면 AWS 계정이 표시됩니다.



==== 링크 연결 기능 향상

* 재고 탭에서 FSx for ONTAP 파일 시스템의 링크를 빠르게 연결할 수 있습니다.
* 이제 BlueXP  워크로드 팩토리에서는 링크 연결에 대체 ONTAP 사용자 자격 증명의 사용을 지원합니다.




==== AWS Secrets Manager에 대한 링크 인증 지원

이제 AWS Secrets Manager의 비밀을 사용하여 링크를 인증할 수 있으므로 BlueXP  워크로드 팩토리얼에 저장된 자격 증명을 사용할 필요가 없습니다.



==== Tracker 응답 지원

이제 추적기는 작업과 관련된 REST API 출력을 볼 수 있도록 API 응답을 제공합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Tracker를 사용하여 작업을 모니터링합니다"]



==== 백업에서 볼륨을 복구할 때의 용량 검증

백업에서 볼륨을 복원할 때 BlueXP  워크로드 팩토리얼은 복원에 필요한 용량이 충분한지 확인하고, 그렇지 않을 경우 SSD 스토리지 계층 용량을 자동으로 추가할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["백업에서 볼륨을 복원합니다"]



==== 대체 ONTAP 사용자 자격 증명 지원

이제 워크로드 팩토리에서 파일 시스템을 생성하여 보안 위험을 최소화할 수 있도록 대체 ONTAP 자격 증명 세트를 지원합니다. fsxadmin 사용자만 사용하는 대신 다른 ONTAP 자격 증명 세트를 선택하거나 fsxadmin 및 vsaadmin 사용자의 암호를 제공하지 않도록 선택할 수 있습니다.



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스와 문서에서는 이제 읽기 권한을 나타내는 데 "읽기 전용"을 사용하고 자동화 권한을 나타내는 데 "읽기/쓰기"를 사용합니다.



=== 데이터베이스 워크로드



==== 향상된 대시보드 기능

* 교차 계정 및 교차 지역 보기는 BlueXP  워크로드 팩토리 콘솔에서 탭 간을 탐색할 때 사용할 수 있습니다. 새로운 뷰를 통해 리소스 관리, 모니터링 및 최적화가 향상됩니다.
* 대시보드의 * potential savings * 타일에서 Amazon Elastic Block Store 또는 Amazon FSx for Windows 파일 서버에서 FSx for ONTAP로 전환하여 저장할 수 있는 항목을 빠르게 검토할 수 있습니다.




==== 데이터베이스 구성에 대해 Ad Hoc 스캔을 사용할 수 있습니다

데이터베이스용 BlueXP  워크로드 팩토리는 관리형 Microsoft SQL Server 인스턴스를 FSx for ONTAP 스토리지로 자동으로 검사하여 잠재적인 구성 문제가 있는지 확인합니다. 이제 매일 스캔하는 것 외에도 언제든지 스캔할 수 있습니다.



==== 온프레미스 평가 기록 제거

Microsoft SQL Server 온-프레미스 호스트의 절감 효과를 살펴본 후 BlueXP  워크로드 공장에서 온-프레미스 호스트 레코드를 제거할 수 있습니다.



==== 최적화 개선 사항



===== 클론 정리

클론 정리 진단 및 문제 해결은 비용이 많이 드는 오래된 클론을 식별하고 관리합니다. 60일이 지난 클론은 BlueXP  워크로드 팩토리 콘솔에서 새로 고치거나 삭제할 수 있습니다.



===== 구성 분석을 연기하고 해제합니다

일부 구성은 데이터베이스 환경에 적용되지 않을 수 있습니다. 이제 특정 구성 분석을 30일 연기하거나 해석을 취소할 수 있습니다.



==== 온프레미스 평가 기록 제거

Microsoft SQL Server 온-프레미스 호스트의 절감 효과를 살펴본 후 BlueXP  워크로드 공장에서 온-프레미스 호스트 레코드를 제거할 수 있습니다.



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스와 문서에서는 이제 읽기 권한을 나타내는 데 "읽기 전용"을 사용하고 자동화 권한을 나타내는 데 "읽기/쓰기"를 사용합니다.



=== VMware 워크로드



==== Amazon EC2 마이그레이션 어드바이저 개선 사항

이 VMware용 BlueXP  워크로드 팩토리에는 Amazon EC2 마이그레이션 조언자 환경이 다음과 같이 개선되었습니다.

* 데이터 소스로서의 NetApp 데이터 인프라 인사이트 *: 이제 워크로드 팩토리가 NetApp 데이터 인프라 통찰력과 직접 연결되어 EC2 마이그레이션 어드바이저 데이터 수집기를 사용할 때 VMware 배포 정보를 수집합니다.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["마이그레이션 관리자를 사용하여 Amazon EC2에 대한 배포 계획을 생성합니다"]



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스와 문서에서는 이제 읽기 권한을 나타내는 데 "읽기 전용"을 사용하고 자동화 권한을 나타내는 데 "읽기/쓰기"를 사용합니다.



=== GenAI 워크로드



==== Amazon Q Business용 NetApp 커넥터 지원

GenAI의 이번 릴리스에서는 Amazon Q Business용 NetApp Connector에 대한 지원이 도입되어 Amazon Q Business용 커넥터를 생성할 수 있습니다. Amazon Bedrock용 GenAI 지식 기반을 구축하는 것보다 초기 구성이 적은 Amazon Q Business AI Assistant를 빠르고 쉽게 활용할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Amazon Q Business용 NetApp 커넥터 만들기"]



==== 향상된 채팅 모델 지원

GenAI는 이제 기술 자료에 대해 다음과 같은 추가 채팅 모델을 지원합니다.

* link:https://docs.mistral.ai/getting-started/models/models_overview/["미스트랄 AI 모델"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titan 텍스트 모델"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llama 모델"^]
* link:https://docs.ai21.com/["Jamba 1.5 모델"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["COHERE 명령 모델"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Deepseek 모델"^]


GenAI는 Amazon Bedrock이 지원하는 각 공급자의 모델을 지원합니다. link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["아마존 Bedrock에서 기반 모델을 지원했습니다"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["GenAI 기술 자료를 만듭니다"]



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스와 문서에서는 이제 읽기 권한을 나타내는 데 "읽기 전용"을 사용하고 자동화 권한을 나타내는 데 "읽기/쓰기"를 사용합니다.



=== 설정 및 관리



==== CloudShell 자동 지원

BlueXP  워크로드 팩토리 CloudShell을 사용하는 경우 명령 입력을 시작하고 Tab 키를 눌러 사용 가능한 옵션을 볼 수 있습니다. 가능성이 여러 개인 경우 CLI에 제안 목록이 표시됩니다. 이 기능은 오류를 최소화하고 명령 실행 속도를 높여 생산성을 향상시킵니다.



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스와 문서에서는 이제 읽기 권한을 나타내는 데 "읽기 전용"을 사용하고 자동화 권한을 나타내는 데 "읽기/쓰기"를 사용합니다.



=== 빌더 작업량



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스와 문서에서는 이제 읽기 권한을 나타내는 데 "읽기 전용"을 사용하고 자동화 권한을 나타내는 데 "읽기/쓰기"를 사용합니다.



== 2025년 04월 04일



=== 데이터베이스 워크로드



==== 최적화 개선 사항

데이터베이스 환경을 최적화할 때 새로운 최적화 평가, 해결 및 여러 리소스 표시를 사용할 수 있습니다.



===== 복구 성능 평가

향상된 기능으로는 데이터 이중화 및 재해 복구 기능이 데이터베이스 환경에 맞게 구성되었는지 확인하기 위한 새로운 복구 성능 평가가 포함됩니다.

* FSx for ONTAP 백업: SQL Server 인스턴스의 볼륨을 지원하는 FSx for ONTAP 파일 시스템이 예약된 FSx for ONTAP 백업을 사용하여 구성되었는지 여부를 분석합니다.
* 지역 간 복제: Microsoft SQL Server 인스턴스를 지원하는 FSx for ONTAP 파일 시스템이 지역 간 복제로 구성되는지 평가합니다.




===== 컴퓨팅 조정

RSS(Receive Side Scaling) 조정은 RSS를 구성하여 여러 프로세서에 걸쳐 네트워크 처리를 분산시키고 효율적인 로드 분산을 보장합니다.



===== 로컬 스냅샷 수정

로컬 스냅샷 해결을 통해 Microsoft SQL Server 인스턴스 볼륨에 대한 스냅샷 정책을 설정하여 데이터 손실 시 데이터베이스 환경의 복원력을 유지합니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["구성 최적화"]



===== 여러 리소스 선택 지원

이제 데이터베이스 구성을 최적화할 때 모든 리소스 대신 특정 리소스를 선택할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["구성 최적화"]



==== 인벤토리 보기가 개선되었습니다

워크로드 팩토리 콘솔의 인벤토리 탭은 Amazon FSx for NetApp ONTAP에서 실행되는 SQL 서버만 포함되도록 간소화되었습니다. 이제 온프레미스에서 Amazon Elastic Block Store 및 Amazon FSx for Windows File Server에서 실행되는 SQL 서버를 탐색 절약 탭에 찾을 수 있습니다.



==== PostgreSQL 서버 배포에 빠른 생성을 사용할 수 있습니다

이 빠른 배포 옵션을 사용하여 HA 구성 및 내장된 모범 사례를 사용하여 PostgreSQL 서버를 생성할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["BlueXP  워크로드 팩터리에서 PostgreSQL 서버를 생성합니다"]



== 2025년 03월 30일



=== VMware 워크로드



==== Amazon EC2 마이그레이션 어드바이저 개선 사항

이 VMware용 BlueXP  워크로드 팩토리에는 Amazon EC2 마이그레이션 조언자 환경이 여러 가지 향상되었습니다.

* * 향상된 볼륨 할당 지침 *: EC2 마이그레이션 어드바이저의 볼륨 할당 정보는 "분류" 및 "패키지" 단계에서 읽기 편이성과 사용성이 향상되었습니다. 각 볼륨에 대한 보다 유용한 정보가 표시되므로 볼륨을 보다 잘 식별하고 볼륨을 할당하는 방법을 결정할 수 있습니다.
* * 데이터 수집기 스크립트 효율성 향상 *: EC2 마이그레이션 어드바이저 데이터 수집기 스크립트는 소규모 VM 배포를 위해 데이터를 수집할 때 CPU 사용을 최적화합니다.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["마이그레이션 관리자를 사용하여 Amazon EC2에 대한 배포 계획을 생성합니다"]



=== 설정 및 관리



==== CloudShell은 ONTAP CLI 명령에 대한 AI에서 생성된 오류 응답을 보고합니다

CloudShell을 사용할 경우 ONTAP CLI 명령을 실행하고 오류가 발생할 때마다 실패 설명, 장애 원인, 상세한 해결 방법 등을 통해 AI에서 생성된 오류에 대한 응답을 받을 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용합니다"]



==== IAM: SimulatePermissionPolicy 권한 업데이트

이제 AWS 계정 자격 증명을 추가하거나 GenAI 워크로드와 같은 새로운 워크로드 기능을 추가할 때 워크로드 팩토리 콘솔에서 권한을 관리할 수 있습니다 `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]



== 2025년 02월 02일



=== 설정 및 관리



==== BlueXP  워크로드 공장 콘솔에서 사용할 수 있는 CloudShell

CloudShell은 BlueXP  워크로드 공장 콘솔의 모든 곳에서 사용할 수 있습니다. CloudShell을 사용하면 BlueXP  계정에 제공한 AWS 및 ONTAP 자격 증명을 사용하고 셸 유사 환경에서 AWS CLI 명령 또는 ONTAP CLI 명령을 실행할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용합니다"]



==== 데이터베이스에 대한 사용 권한 업데이트

이제 데이터베이스에 대해 _READ_MODE에서 다음 권한을 사용할 수 `iam:SimulatePrincipalPolicy` 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]



== 2024년 12월 01일



=== 빌더 작업량



==== 빌더 워크로드 초기 릴리즈

Builders용 BlueXP  워크로드 팩토리에서는 소프트웨어 버전 사용 및 액세스를 간소화하여 사용자 지정 툴이나 스크립트가 필요하지 않습니다. 소프트웨어 버전을 Perforce Helix Core와 통합된 즉각적인 클론으로 사용하여 개발 프로세스를 위한 편리한 작업 공간으로서 시간과 리소스를 절약할 수 있습니다.

초기 릴리스에는 프로젝트 및 작업 영역을 관리하고 Codebox를 사용하여 작업을 자동화하는 기능이 포함되어 있습니다. 또한 Builders를 Perforce Helix Core와 통합하여 각 프로젝트의 다양한 버전을 관리하고 프로젝트 간에 신속하게 전환할 수 있습니다.
