= Agentic AI 기반 오류 로그 분석기
:allow-uri-read: 




=== Agentic AI 기반 오류 로그 분석기

Agentic AI 기반 오류 로그 분석기는 고급 머신 러닝 알고리즘을 활용하여 로그 파일의 오류를 자동으로 감지하고 분석하는 새로운 기능입니다. 이 도구는 로그에서 식별된 패턴을 기반으로 개발자에게 실행 가능한 통찰력과 권장 사항을 제공하여 문제 해결 프로세스를 간소화하는 것을 목표로 합니다.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Agentic AI 기반 오류 로그 분석기에 대해 자세히 알아보세요."]



=== 오라클 지원

Workload Factory에는 Oracle 데이터베이스에 대한 지원이 포함되어 있습니다. 워크로드 팩토리 콘솔에서는 인벤토리에서 Oracle 데이터베이스를 보고, 워크로드 팩토리의 고급 기능을 사용하기 위해 데이터베이스를 등록하고, 잘 설계된 기능을 사용하여 모범 사례에 맞춰 Oracle 데이터베이스를 분석할 수 있습니다. 잘 설계된 분석을 통해 Oracle 데이터베이스의 스토리지 구성이 최적화되었는지 확인할 수 있습니다. 이 정보를 사용하면 데이터베이스 배포에 대한 정보에 입각한 결정을 내리고 데이터베이스가 효율적으로 실행되는지 확인할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["워크로드 팩토리에서 잘 설계된 데이터베이스 구성을 구현합니다."]



=== 2세대 FSx for ONTAP 파일 시스템에서 Microsoft SQL Server 배포 지원

Workload Factory는 2세대 FSx for ONTAP 파일 시스템에서 Microsoft SQL Server 배포를 지원합니다. 이 향상된 기능을 사용하면 SQL Server 작업 부하를 관리하는 동시에 2세대 파일 시스템에서 제공되는 최신 기능과 성능 개선 사항을 활용할 수 있습니다.



=== SQL Server 보호를 위한 Windows 인증

Windows 자격 증명을 사용하여 Microsoft SQL Server 인스턴스를 인증하는 작업은 BlueXP backup and recovery 통해 Microsoft SQL Server 호스트를 보호하기 위한 워크플로에 포함되어 있습니다. 이 단계는 수동으로 완료해야 하는 필수 단계였습니다. 대신 Windows 자격 증명을 사용하여 워크로드 팩토리에 호스트를 등록하지 않은 경우 관리자 액세스 권한으로 Windows 자격 증명을 공유하라는 메시지가 표시됩니다.

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["워크로드 팩토리 콘솔을 통해 Microsoft SQL Server 워크로드를 보호하는 방법을 알아보세요."] .



=== 잘 설계된 분석에는 SQL Server에 대한 MTU 정렬이 포함됩니다.

잘 설계된 분석은 FSx for ONTAP 스토리지의 Microsoft SQL Server에서 엔드포인트 간의 최대 전송 단위(MTU) 정렬 오류를 평가하고 수정합니다. MTU 설정을 맞추면 네트워크 성능을 최적화하고 SQL Server 작업 부하의 대기 시간을 줄이는 데 도움이 됩니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["워크로드 팩토리에서 잘 설계된 데이터베이스 구성을 구현합니다."]
