= 자동 용량 관리 개선
:allow-uri-read: 




=== 자동 용량 관리 개선

자동 용량 관리가 설정되면 BlueXP  워크로드 팩토리에서는 이제 파일 시스템이 용량 임계값에 도달했는지 2시간마다 아닌 30분마다 확인합니다.

또한 워크로드 팩토리에서는 볼륨에서 사용 가능한 inode를 검색하고 구성된 자동 용량 관리 임계값에 따라 해당 수를 늘립니다.

용량 임계값에 도달하면 프로비저닝된 IOPS 설정이 더 이상 영향을 받지 않습니다.



=== 변경 불가능한 스냅샷

이제 스냅샷을 잠가 특정 보존 기간 동안 변경 불가능한 상태로 만들 수 있습니다. 잠금은 무단 액세스 및 스냅샷의 악의적인 삭제를 방지합니다. 스냅샷 정책 생성 중, 수동 스냅샷 생성 시 및 스냅샷 생성 후 변경 불가능한 스냅샷을 설정할 수 있습니다.



=== 변경 불가능한 파일이 업데이트됩니다

이제 변경 불가능한 파일 구성을 보존 정책, 보존 기간, 자동 커밋 기간 및 볼륨 추가 모드와 같이 변경할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-immutable-files.html["변경 불가능한 파일을 관리합니다"^]



=== 데이터 복제 기능 개선

* 교차 계정 복제: 두 AWS 계정 간의 복제는 BlueXP  워크로드 팩토리 콘솔과 복제 관리에서 지원됩니다.
* 데이터 보호 볼륨 복제: 이제 데이터 보호 볼륨은 복제된 볼륨에서 볼륨을 복제할 때 계단식 복제를 지원합니다.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["데이터 보호 볼륨을 복제합니다"]

* 복제 일시 중지 및 다시 시작: 소스 볼륨에서 대상 볼륨으로 예약된 복제 업데이트를 일시 중지(중지)한 다음 준비가 되면 복제 일정을 재개할 수 있습니다. 일시 중지 중에는 소스 볼륨과 타겟 볼륨이 독립적이며 타겟 볼륨이 읽기 전용에서 읽기-쓰기로 전환됩니다.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/pause-resume-replication.html["복제 관계를 일시 중지했다가 다시 시작합니다"]





=== Tracker의 CloudShell 이벤트

이제 Tracker에서 CloudShell 이벤트를 추적할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Tracker를 사용하여 운영을 모니터링하고 추적하는 방법에 대해 알아봅니다"]
