= 최적화 개선 사항
:allow-uri-read: 




=== 최적화 개선 사항

데이터베이스 환경을 최적화할 때 새로운 최적화 평가, 해결 및 여러 리소스 표시를 사용할 수 있습니다.



==== 복구 성능 평가

향상된 기능으로는 데이터 이중화 및 재해 복구 기능이 데이터베이스 환경에 맞게 구성되었는지 확인하기 위한 새로운 복구 성능 평가가 포함됩니다.

* FSx for ONTAP 백업: SQL Server 인스턴스의 볼륨을 지원하는 FSx for ONTAP 파일 시스템이 예약된 FSx for ONTAP 백업을 사용하여 구성되었는지 여부를 분석합니다.
* 지역 간 복제: Microsoft SQL Server 인스턴스를 지원하는 FSx for ONTAP 파일 시스템이 지역 간 복제로 구성되는지 평가합니다.




==== 컴퓨팅 조정

RSS(Receive Side Scaling) 조정은 RSS를 구성하여 여러 프로세서에 걸쳐 네트워크 처리를 분산시키고 효율적인 로드 분산을 보장합니다.



==== 로컬 스냅샷 수정

로컬 스냅샷 해결을 통해 Microsoft SQL Server 인스턴스 볼륨에 대한 스냅샷 정책을 설정하여 데이터 손실 시 데이터베이스 환경의 복원력을 유지합니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["구성 최적화"]



==== 여러 리소스 선택 지원

이제 데이터베이스 구성을 최적화할 때 모든 리소스 대신 특정 리소스를 선택할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["구성 최적화"]



=== 인벤토리 보기가 개선되었습니다

워크로드 팩토리 콘솔의 인벤토리 탭은 Amazon FSx for NetApp ONTAP에서 실행되는 SQL 서버만 포함되도록 간소화되었습니다. 이제 온프레미스에서 Amazon Elastic Block Store 및 Amazon FSx for Windows File Server에서 실행되는 SQL 서버를 탐색 절약 탭에 찾을 수 있습니다.



=== PostgreSQL 서버 배포에 빠른 생성을 사용할 수 있습니다

이 빠른 배포 옵션을 사용하여 HA 구성 및 내장된 모범 사례를 사용하여 PostgreSQL 서버를 생성할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["BlueXP  워크로드 팩터리에서 PostgreSQL 서버를 생성합니다"]
