= BlueXP 워크로드 팩토리 알림 서비스 지원
:allow-uri-read: 




=== BlueXP 워크로드 팩토리 알림 서비스 지원

BlueXP 워크로드 팩토리 알림 서비스를 사용하면 워크로드 팩토리가 BlueXP 알림 서비스 또는 Amazon SNS 주제로 알림을 전송할 수 있습니다. BlueXP 알림으로 전송된 알림은 BlueXP 알림 패널에 표시됩니다. 워크로드 팩토리가 Amazon SNS 주제에 알림을 게시하면 해당 주제 구독자(예: 사용자 또는 다른 애플리케이션)는 해당 주제에 대해 구성된 엔드포인트(예: 이메일 또는 SMS 메시지)에서 알림을 수신합니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXP 워크로드 팩토리 알림 구성"^]



=== 스토리지 대시보드 개선

워크로드 팩토리 콘솔의 스토리지 대시보드에 새로운 절감 기회 카드가 추가되었습니다. 대시보드 상단의 카드는 Amazon Elastic Block Store(EBS), Amazon FSx for Windows File Server, Amazon Elastic File Systems(EFS)에서 실행되는 스토리지 환경에 대한 절감 기회 수를 대시보드 하단에는 Amazon 스토리지 서비스별 절감 기회(EBS, FSx for Windows File Server, EFS)를 표시하는 세 개의 새로운 카드가 추가되었습니다 모든 카드에서 절감 기회를 더 자세히 살펴볼 수 있습니다.

FSx for ONTAP 보호 범위 카드와 복제 관계 상태 카드를 통해 FSx for ONTAP 파일 시스템에 부분적으로 보호된 볼륨이 있는지 확인하고 복제 관계 관련 문제를 조사할 수 있습니다. 두 경우 모두 문제 해결을 위한 조치를 취할 수 있습니다.



=== 볼륨 탭 향상

워크로드 팩토리 콘솔의 볼륨 탭이 개선되어 FSx for ONTAP 파일 시스템을 더욱 포괄적으로 볼 수 있습니다. SSD 용량, 용량 풀, NetApp Autonomous Ransomware Protection with AI(ARP/AI)를 위한 새로운 카드가 추가되었습니다. 이 카드는 파일 시스템의 모든 볼륨에 대한 용량 사용률과 ARP/AI 보호 기능을 요약합니다.



=== 2세대 Amazon FSx for NetApp ONTAP 파일 시스템 지원

Workload Factory는 이제 2세대 Amazon FSx for NetApp ONTAP 파일 시스템을 지원합니다. Workload Factory 콘솔에서 2세대 파일 시스템을 생성, 관리 및 모니터링할 수 있습니다. 모든 신규 상용 리전이 지원됩니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Workload Factory에서 2세대 파일 시스템 생성"]



=== 볼륨 용량 재조정을 위한 FlexVol 볼륨 지원

FlexVol 볼륨은 워크로드 팩토리 콘솔에서 확인할 수 있습니다. FlexVol 볼륨의 잔액을 확인하고, 새 파일 추가 및 파일 증가로 인해 시간이 지남에 따라 용량 불균형이 발생할 경우 FlexVol 볼륨을 재조정하여 용량을 재분배할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["FlexVol 볼륨의 용량 재조정"]



=== 용어 업데이트

워크로드 팩토리 콘솔에서 "자율 랜섬웨어 보호"(ARP)라는 용어가 "AI를 통한 NetApp 자율 랜섬웨어 보호"(ARP/AI)로 업데이트되었습니다.



=== 새 볼륨에 대해 기본적으로 ARP/AI가 활성화됨

워크로드 팩토리 콘솔에서 새 볼륨을 생성하면 파일 시스템에 ARP/AI 정책이 있는 경우 NetApp Autonomous Ransomware Protection with AI(ARP/AI)가 기본적으로 활성화됩니다. 즉, AI 기반 탐지 및 대응 기능을 사용하여 볼륨이 랜섬웨어 공격으로부터 자동으로 보호됩니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["워크로드 팩토리에서 볼륨을 생성합니다."]



=== 변경 불가능한 파일에 대한 복제 지원

Workload Factory는 중요한 데이터를 실수로 삭제하거나 랜섬웨어와 같은 악의적인 공격으로부터 보호하기 위해 한 FSx for ONTAP 시스템에서 다른 FSx for ONTAP 파일 시스템으로 변경 불가능한 볼륨을 복제하는 기능을 지원합니다. 대상 볼륨과 호스트 파일 시스템은 변경 불가능하거나 잠기게 되며, 대상 파일 시스템의 모든 데이터는 보존 기간이 끝날 때까지 수정하거나 삭제할 수 없습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["복제 관계를 만드는 방법을 알아보세요"]



=== 링크 생성 중 IAM 실행 역할 및 권한 관리

이제 워크로드 팩토리 콘솔에서 링크를 생성하여 IAM 실행 역할과 연결된 권한 정책을 관리할 수 있습니다. 링크는 워크로드 팩토리 계정과 하나 이상의 FSx for ONTAP 파일 시스템 간의 연결을 설정합니다. IAM 실행 역할과 링크 권한을 할당하는 데는 자동 또는 사용자 지정, 두 가지 옵션이 있습니다. 워크로드 팩토리에서 실행 역할과 연결된 권한 정책을 관리하면 더 이상 타사 코드를 사용할 필요가 없습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Lambda 링크를 사용하여 FSx for ONTAP 파일 시스템에 연결합니다"]
