= 복제 관계 탭 개선
:allow-uri-read: 




=== 복제 관계 탭 개선

*복제 관계* 탭에서 복제 관계에 대한 자세한 정보를 제공하기 위해 복제 관계 표에 여러 개의 새 열을 추가했습니다. 이제 표에는 다음 열이 포함됩니다.

* SnapMirror 정책
* 소스 파일 시스템
* 대상 파일 시스템
* 관계의 상태
* 마지막 환승 시간




=== AI(ARP/AI)를 통한 NetApp 자율 랜섬웨어 보호 기능 향상

이번 릴리스에서는 랜섬웨어 보호 기능에 인공 지능을 통합한 것을 더 잘 반영하기 위해 "NetApp 자율형 랜섬웨어 보호(ARP/AI)"라는 업데이트된 용어를 소개합니다.

또한 ARP/AI에 다음과 같은 개선 사항이 적용되었습니다.

* 볼륨 수준 ARP/AI: 이제 볼륨 수준에서 ARP/AI를 활성화하여 FSx for ONTAP 파일 시스템 내의 특정 볼륨을 보호할 수 있습니다.
* 자동 스냅샷 생성: ARP/AI 정책을 설정하여 자동 스냅샷을 생성하고 ARP/AI가 활성화된 볼륨에 대해 스냅샷을 생성하는 빈도를 정의하여 데이터 보호 전략을 강화할 수 있습니다.
* 변경 불가능한 스냅샷: ARP/AI는 이제 삭제나 수정이 불가능한 변경 불가능한 스냅샷을 지원하여 랜섬웨어 공격에 대한 보안을 한층 강화했습니다.
* 탐지: 볼륨 수준에서 높은 엔트로피 데이터 전송률, 파일 생성률, 파일 이름 변경률, 파일 삭제률, 동작 분석과 이전에 본 적이 없는 파일 확장자 등 다양한 탐지 방법을 포함하여 이상 징후와 잠재적인 랜섬웨어 공격을 탐지하는 데 도움이 됩니다.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["AI(ARP/AI)를 탑재한 NetApp Autonomous Ransomware Protection으로 데이터를 보호하세요"]



=== 잘 설계된 분석 업데이트

Workload Factory는 이제 다음 구성에 대해 FSx for ONTAP 파일 시스템을 분석합니다.

* 장기 보존 데이터 안정성: 소스 볼륨의 스냅샷 정책에 할당된 레이블이 장기 보존 정책에 할당된 레이블과 동일한지 확인합니다. 레이블이 동일하면 소스 볼륨과 대상 볼륨 간의 데이터 복제가 안정적으로 이루어집니다.
* AI(ARP/AI)를 탑재한 NetApp 자율형 랜섬웨어 보호: 파일 시스템에서 ARP/AI가 활성화되어 있는지 확인합니다. 이 기능은 랜섬웨어 공격을 탐지하고 복구하는 데 도움이 됩니다.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ONTAP 파일 시스템용 FSx의 잘 설계된 상태를 확인하세요."]



=== 잘 설계된 분석에서 구성을 해제합니다.

이제 잘 설계된 분석에서 하나 이상의 구성을 해제할 수 있습니다. 이를 통해 현재 처리하고 싶지 않은 특정 구성을 무시할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["잘 설계된 분석에서 구성을 해제합니다."]



=== 링크 생성을 위한 Terraform 지원

이제 Codebox에서 Terraform을 사용하여 FSx for ONTAP 파일 시스템과의 연결을 위한 링크를 생성할 수 있습니다. 이 기능은 수동으로 링크를 만드는 사용자를 위한 것입니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Lambda 링크를 사용하여 FSx for ONTAP 파일 시스템에 연결합니다"]



=== 저장소 절약 탐색을 위한 새로운 지역 지원

이제 다음과 같은 새로운 지역에서 Amazon Elastic Block Store(EBS), FSx for Windows File Server 및 Elastic File Systems(EFS)에 대한 절감을 탐색할 수 있습니다.

* 멕시코
* 태국




=== SMB/CIFS 주식 생성 및 관리 기능 향상

이제 볼륨 내의 디렉토리를 가리키는 SMB/CIFS 공유를 만들 수 있습니다. 볼륨 내에서 어떤 공유가 있는지, 공유가 가리키는 곳은 어디인지, 특정 사용자와 그룹에 부여된 권한은 무엇인지 확인할 수 있습니다.

데이터 보호 볼륨의 경우, SMB/CIFS 공유를 생성하는 흐름에 이제 마운트 목적으로 볼륨에 대한 연결 경로를 생성하는 작업이 포함됩니다.

link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_grogu-5684-wa-dismiss/manage-cifs-share.html#create-a-cifs-share-for-a-volume["볼륨에 대한 CIFS 공유 만들기"]
