= BlueXP 워크로드 팩토리 알림 서비스 지원
:allow-uri-read: 




=== BlueXP 워크로드 팩토리 알림 서비스 지원

BlueXP 워크로드 팩토리 알림 서비스를 사용하면 워크로드 팩토리가 BlueXP 알림 서비스 또는 Amazon SNS 주제로 알림을 전송할 수 있습니다. BlueXP 알림으로 전송된 알림은 BlueXP 알림 패널에 표시됩니다. 워크로드 팩토리가 Amazon SNS 주제에 알림을 게시하면 해당 주제 구독자(예: 사용자 또는 다른 애플리케이션)는 해당 주제에 대해 구성된 엔드포인트(예: 이메일 또는 SMS 메시지)에서 알림을 수신합니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXP 워크로드 팩토리 알림 구성"^]

Workload Factory는 데이터베이스에 대해 다음과 같은 알림을 제공합니다.

* 잘 구성된 보고서
* 호스트 배포




=== 인스턴스 등록을 위한 온보딩 향상

데이터베이스용 워크로드 팩토리는 Amazon FSx for NetApp ONTAP 스토리지에서 실행되는 인스턴스를 등록하는 온보딩 프로세스를 개선했습니다. 이제 등록할 인스턴스를 대량으로 선택할 수 있습니다. 인스턴스가 등록되면 워크로드 팩토리 콘솔에서 데이터베이스 리소스를 만들고 관리할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["인스턴스 관리"]



=== Microsoft Multipath I/O 시간 초과 설정에 대한 분석 및 수정

이제 데이터베이스 인스턴스의 잘 설계된 상태에는 Microsoft Multipath I/O(MPIO) 시간 초과 설정에 대한 분석 및 수정 사항이 포함됩니다. MPIO 시간 제한을 60초로 설정하면 FSx for ONTAP 스토리지 연결 및 장애 조치(failover) 중 안정성이 보장됩니다. MPIO 설정이 제대로 설정되지 않은 경우, Workload Factory에서 MPIO 시간 제한 값을 60초로 설정하는 수정 사항을 제공합니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["워크로드 팩토리에서 잘 설계된 데이터베이스 구성을 구현합니다."]



=== 인스턴스 인벤토리의 그래픽 향상

인스턴스 인벤토리 화면에서 처리량, IOPS 등 다양한 리소스 활용도 그래프가 이제 7일치 데이터를 표시하므로 워크로드 팩토리 콘솔에서 SQL 노드의 성능을 보다 효율적으로 모니터링할 수 있습니다. SQL 노드에서 수집된 성능 지표는 Amazon CloudWatch에 저장되어 Logs Insights에 활용하거나 환경의 다른 분석 서비스와 통합할 수 있습니다.

인벤토리 내의 인스턴스 및 데이터베이스 탭에서 보호에 대한 설명과 시각화를 개선했습니다.



=== 워크로드 팩토리에서 Windows 인증 지원

이제 워크로드 팩토리는 Windows 인증 사용자를 사용하여 인스턴스를 등록하고 관리 기능의 이점을 활용하는 SQL Server 인증을 지원합니다.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["데이터베이스의 워크로드 팩토리에 인스턴스 등록"]
