= Amazon Elastic Block Store(EBS)의 스토리지 계산기에서 비용 절감을 최적화하세요.
:allow-uri-read: 




=== Amazon Elastic Block Store(EBS)의 스토리지 계산기에서 비용 절감을 최적화하세요.

Workload Factory는 EBS 성능 사용량을 분석한 후 가장 적합하고 비용 효율적인 FSx for ONTAP 구성을 제안해 FSx for ONTAP 으로 전환하면 더 많은 비용을 절감할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/explore-savings.html#explore-savings-for-detected-storage-environments["Workload Factory 콘솔에서 감지된 스토리지 환경에 대한 절감 효과를 살펴보세요."]



=== 파일 시스템 인벤토리에서 리소스 화면에 빠르게 액세스

FSx for ONTAP 인벤토리에서 파일 시스템 이름(이제 하이퍼링크)을 선택하면 FSx for ONTAP 파일 시스템 리소스 화면으로 빠르게 이동할 수 있습니다.



=== Workload Factory 콘솔에서 캐시 관계 검색

FSx for ONTAP 파일 시스템과 다른 유형의 ONTAP 스토리지(온프레미스 시스템, Cloud Volumes ONTAP, FSx for ONTAP) 사이에 _캐시_ 관계가 있는 경우 Workload Factory 콘솔에서 이를 검색하고 볼 수 있습니다. 이를 통해 데이터 흐름을 더 잘 이해하고, 캐시 활용도를 최적화하고, 분산 환경 전반에서 효율성을 개선할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/discover-cache-volumes.html["Workload Factory 콘솔에서 캐시 관계를 검색하고 확인하세요."]



=== 잘 설계된 분석 업데이트

Workload Factory는 이제 다음 구성에 대해 FSx for ONTAP 파일 시스템을 분석합니다.

볼륨 파일 용량 사용률 임계값: 파일 용량 임계값이 80% 이하로 설정되어 있는지 확인합니다. 이렇게 하면 파일 시스템의 공간 부족을 방지할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ONTAP 파일 시스템용 FSx의 잘 설계된 상태를 확인하세요."]



==== 구성 문제에 대한 작업 개선

FSx for ONTAP 파일 시스템의 대시보드에 있는 *잘 설계된 분석* 탭에서 파일 시스템의 전체 구성을 해제하는 대신, 파일 시스템 내에서 하나 이상의 볼륨을 선택하여 수정, 해제 또는 다시 활성화할 수도 있습니다.



=== 저장에 대한 추가 알림

NetApp Workload Factory 알림 서비스에는 잘 설계된 구성 문제에 대한 알림이 매주 포함됩니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html#notification-types-and-messages["Workload Factory 설정 및 관리 설명서의 알림 유형 및 메시지"]



=== 변경 불가능한 파일은 권한 있는 삭제를 지원합니다.

이 기능을 사용하면 FSx for ONTAP 파일 시스템에서 변경 불가능한 파일에 대한 권한 있는 삭제 액세스를 구성할 수 있습니다. 이를 통해 중요한 데이터가 실수로 또는 악의적으로 삭제되는 것을 방지하는 동시에, 권한이 있는 사용자가 잠금을 해제하고 필요에 따라 해당 파일을 삭제할 수 있습니다. 볼륨 생성 중이나 기존 볼륨에 대해 권한 있는 삭제를 활성화할 수 있습니다.
