= Amazon Elastic Block Store(EBS) 데이터베이스 계산기에서 비용 절감 최적화
:allow-uri-read: 




=== Amazon Elastic Block Store(EBS) 데이터베이스 계산기에서 비용 절감 최적화

두 가지 새로운 계산기 기능은 EBS 스토리지를 사용하여 여러 인스턴스를 실행할 때 비용 절감 분석을 개선하여 FSx for ONTAP 으로 전환하면 더 많은 비용을 절감할 수 있습니다.

* Workload Factory는 하나의 FSx for ONTAP 파일 시스템에서 여러 데이터베이스 호스트를 위한 통합 스토리지 솔루션을 제공합니다. 이러한 통합을 통해 여러 데이터베이스 호스트에 필요한 파일 시스템 수가 줄어들어 스토리지 비용이 최적화되고, 결과적으로 비용 절감 효과가 더욱 커집니다.
* Workload Factory는 EBS 성능 사용량을 분석한 후 ONTAP 구성에 가장 적합하고 비용 효율적인 FSx를 제안합니다.


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["감지된 EBS 호스트에 대한 절감액 살펴보기"]



=== 잘 설계된 대시보드에 사용 가능한 Excel 보고서

잘 설계된 대시보드의 Excel 보고서를 다운로드할 수 있습니다. 이 보고서는 데이터베이스 리소스에 대한 잘 설계된 상태와 운영 체제 및 ONTAP 에 대한 하위 구성을 포함한 모든 리소스 구성에 대한 권장 사항을 제공합니다.



=== Oracle 데이터베이스에 사용 가능한 오류 로그 분석기

Agentic AI 기반 오류 로그 분석기는 Oracle 데이터베이스에서 사용할 수 있습니다. 이 기능은 고급 머신 러닝 알고리즘을 활용하여 로그 파일의 오류를 자동으로 감지하고 분석합니다. 이 도구는 로그에서 식별된 패턴을 기반으로 개발자에게 실행 가능한 통찰력과 권장 사항을 제공하여 문제 해결 프로세스를 간소화하는 것을 목표로 합니다.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Agentic AI 기반 오류 로그 분석기에 대해 자세히 알아보세요."]



=== Oracle을 위한 잘 설계된 분석

잘 설계된 분석에는 두 가지 새로운 스토리지 크기 구성이 포함되어 있습니다. 분석은 기존 Oracle 데이터베이스 배포에 대한 스왑 공간 할당 및 파일 시스템 여유 공간과 관련된 구성 문제를 평가하고 수정합니다.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Workload Factory에서 잘 설계된 데이터베이스 구성을 구현합니다."]
