= Amazon Nova Foundation 모델 지원
:allow-uri-read: 




=== Amazon Nova Foundation 모델 지원

GenAI는 이제 Amazon Nova 기반 모델을 지원합니다. Amazon Nova Micro, Amazon Nova Lite 및 Amazon Nova Pro가 지원됩니다.

link:https://docs.netapp.com/us-en/workload-genai/requirements.html["GenAI 요구 사항"]



=== 데이터 원본에 대한 파일 형식 필터링

GenAI는 이제 데이터 소스를 추가할 때 데이터 소스 스캔에 포함할 특정 파일 유형을 선택할 수 있도록 지원합니다.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["기술 문서에 데이터 원본을 추가합니다"]



=== 데이터 원본에 대한 파일 수정 날짜 필터링

GenAI는 이제 데이터 소스를 추가할 때 수정 날짜별로 데이터 소스 스캔에 포함할 파일 필터링을 지원합니다. 포함된 파일의 수정 날짜 범위를 선택할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["기술 문서에 데이터 원본을 추가합니다"]



=== 이미지 파일 지원 및 PDF 파일 지원 향상

GenAI는 이제 PDF 파일 내에서 이미지 파일 및 이미지 스캔을 지원합니다(다중 모드 파일 지원이라고도 함). 이미지 파일을 선택하면 이미지의 텍스트가 데이터 원본으로 스캔되어 데이터로 사용됩니다. 이 기능에는 PDF 문서 내의 이미지가 포함됩니다. PDF 파일 형식을 포함하면 각 PDF 내의 이미지가 텍스트를 스캔하고 해당 텍스트가 데이터 원본의 정보에 포함됩니다.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["기술 문서에 데이터 원본을 추가합니다"]



=== 하이브리드 검색 및 리랭크 지원

이제 GenAI는 하이브리드 검색을 사용하여 검색 결과의 관련성을 높이고 결과를 재평가합니다. 하이브리드 검색은 키워드 검색과 벡터 및 의미론적 검색을 결합합니다. 표준 키워드 검색 결과는 유사한 일치 및 언어적 뉘앙스로 보강되어 관련성을 향상시킵니다. GenAI는 검색 결과의 순위를 다시 지정하고 관련성이 가장 높은 결과만 반환합니다.

link:https://docs.netapp.com/us-en/workload-genai/ai-workloads-overview.html#benefits-of-using-genai-to-create-generative-ai-applications["GenAI를 위한 BlueXP  워크로드 팩토리에 대해 알아보십시오"]
