= 캐시 볼륨 관리
:allow-uri-read: 




=== 캐시 볼륨 관리

Workload Factory 콘솔에서 다음과 같은 캐시 볼륨 관리 작업을 수행할 수 있습니다.

* 캐시 이름 편집
* 캐시 볼륨의 용량을 늘리세요
* 캐시 볼륨에 대한 마운트 경로 또는 내보내기 정책 편집
* 캐시 볼륨에 대한 캐싱 방법 또는 모드를 변경합니다.
* 캐시 볼륨 미리 채우기
* 캐시 볼륨 삭제


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["캐시 볼륨 관리"]



=== 자동 inode 관리 가능

자동 용량 관리를 활성화하지 않고도 자동 inode 관리를 활성화할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["자동 inode 관리 활성화"]



=== 용량 및 inode 사용량에 대한 임계값 경고 설정

용량 및 inode 사용량에 대한 임계값 경고를 사용할 수 있습니다. 자동 용량 또는 inode 관리를 활성화할 때 이러한 임계값을 설정할 수 있습니다. 이 설정을 사용하려면 다음을 사용하여 알림을 구성해야 합니다.link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory 알림 서비스"^] .



=== 볼륨 크기 감소 가능

NetApp Workload Factory 에서 NFS 및 SMB/CIFS 볼륨의 크기를 줄일 수 있습니다. 이 기능을 사용하면 현재 용량으로는 더 이상 필요하지 않은 볼륨의 크기를 줄여서 스토리지 리소스를 보다 효과적으로 관리할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["볼륨의 용량을 줄이세요"]



=== ONTAP 리소스 상태를 위한 향상된 FSx

Workload Factory는 리소스의 실제 문제에 대한 설명을 포함하도록 "잘못 구성된" 리소스 상태를 개선했습니다.



=== 잘 설계된 분석 업데이트

Workload Factory는 다음 구성에 대해 FSx for ONTAP 파일 시스템을 분석합니다.

* 볼륨 사용률이 거의 가득 찼습니다. 볼륨이 파일 용량의 80% 이상을 사용하고 있는지 확인합니다. 이를 통해 추가 용량이 필요할 수 있는 볼륨을 식별하는 데 도움이 됩니다.
* 볼륨에 대한 무단 액세스: NFS 또는 SMB/CIFS 마운트 경로를 사용하여 iSCSI 볼륨에 액세스할 수 있는지 확인하고 보안 위험을 방지하기 위해 볼륨에 대한 무단 액세스를 제거할 수 있습니다.




=== Storage용 Workload Factory에 대한 권한 변경

Workload Factory는 특정 작업에 필요한 권한에 대한 명확성을 제공하고 필요한 권한만 선택할 수 있는 세분성을 제공합니다. 자격 증명을 추가하면 이전 권한 모델인 _읽기 전용_ 및 _읽기/쓰기_ 대신 세 가지 권한 옵션 중에서 선택할 수 있습니다. 새로운 권한 모델은 권한 정책을 다음과 같이 구분합니다.

* _보기, 계획 및 분석_: FSx for ONTAP 파일 시스템을 보고, 시스템 상태에 대해 알아보고, 시스템에 맞게 잘 설계된 분석을 받고, 절감 방안을 알아보세요.
* _운영 및 수정_: 파일 시스템 용량을 조정하고 파일 시스템 구성에 대한 문제를 해결하는 등의 운영 작업을 수행합니다.
* _파일 시스템 생성 및 삭제_: FSx for ONTAP 파일 시스템과 스토리지 VM을 생성하고 삭제합니다.


자격 증명을 추가할 때 Workload Factory에 제공하려는 액세스 수준에 따라 이러한 권한 정책 중 하나 이상을 선택할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["워크로드 팩토리 권한 참조"]



=== ONTAP 사이버 볼트 지원을 위한 FSx

FSx for ONTAP 을 사이버 볼트 아키텍처의 소스 또는 대상으로 사용하여 사이버 볼트를 생성할 수 있습니다. 사이버 금고는 중요한 데이터를 저장하기 위한 안전하고 격리된 환경을 제공하여 랜섬웨어 및 기타 사이버 위협으로부터 데이터를 보호합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["FSx for ONTAP 사용하여 사이버 볼트 설정"]
