= BlueXP workload factory NetApp 워크로드 팩토리로 변경되었습니다.
:allow-uri-read: 




=== BlueXP workload factory NetApp 워크로드 팩토리로 변경되었습니다.

BlueXP 데이터 인프라 관리에 있어서의 역할을 더 잘 반영하도록 이름이 바뀌고 재설계되었습니다. 결과적으로 BlueXP workload factory NetApp 워크로드 팩토리로 이름이 변경되었습니다.



=== Amazon Q Business용 NetApp 커넥터에서 일반 NFS/SMB 데이터 소스 추가 지원

Workload Factory API를 사용하면 이제 일반 NFSv3, NFSv4 또는 SMB 공유의 데이터 소스를 Amazon Q Business용 NetApp Connector에 추가할 수 있습니다. 이를 통해 Amazon FSx for NetApp ONTAP 이외의 파일 시스템에서 호스팅되는 볼륨에 저장된 파일을 포함할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Amazon Q Business용 NetApp 커넥터 만들기"]

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["커넥터에 데이터 소스 추가"]



=== 지식 기반을 위한 고급 채팅 구성

이제 지식 기반의 채팅 모델에 적용할 수 있는 고급 채팅 설정(응답 길이, 온도, 추론 설정 등)을 구성할 수 있습니다. 최근성 및 수정 시간 설정, 고급 검색 설정, 시스템 프롬프트 등 일부 설정은 Workload Factory API를 통해서만 사용할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["GenAI 기술 자료를 만듭니다"]



=== 이제 임베딩, 채팅 및 재순위 지정 모델에 대한 추론 유형 선택이 지원됩니다.

선택한 임베딩, 채팅 또는 재순위 지정 모델에 추론 설정이 있는 경우 이제 추론 유형을 선택할 수 있습니다. 이를 통해 사용자의 필요에 맞게 챗봇 성능과 리소스 요구 사항을 더 잘 조정할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["GenAI 기술 자료를 만듭니다"]
