= 블록 디바이스 클론
:allow-uri-read: 




=== 블록 디바이스 클론

Workload Factory는 블록 디바이스용 클론을 제공하여 용량, 액세스 및 수명 주기를 제어하면서 쓰기 가능하고 효율적인 데이터 복사본을 신속하게 프로비저닝할 수 있도록 지원합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["NetApp Workload Factory에서 블록 스토리지를 관리합니다"]



=== 블록 디바이스의 EC2 태그

블록 장치 테이블에 이제 각 블록 장치를 사용하는 EC2 호스트의 태그를 보여주는 열이 추가되었습니다. 이를 통해 문제 해결이나 감사 중에 어떤 호스트가 각 블록 장치를 사용하는지 쉽게 파악할 수 있습니다.

각 블록 디바이스에 태그를 생성하려면 제공된 사용자 스크립트를 사용하여 EC2 인스턴스를 배포하십시오.

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/ec2-user-data-iscsi-create-and-mount["블록 디바이스에 태그를 할당하는 EC2 사용자 데이터 스크립트"]



=== FSx for ONTAP 파일 시스템의 용량 추세

FSx for ONTAP 파일 시스템 개요에서 SSD 용량 추세를 직접 확인하세요. 용량 관리를 위한 새 카드는 지난달의 사용량 추세를 보여줍니다. 이 분석은 실제 용량과 할당된 용량을 비교하여 리소스 사용량을 쉽게 평가할 수 있도록 합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-capacity-automatically.html["NetApp Workload Factory에서 용량을 자동으로 관리하세요"]



=== FSx for ONTAP 파일 시스템의 Well-Architected 상태에 대한 PDF 보고서

분석이 완료되면 기록 보관용 또는 팀과 공유하기 위해 FSx for ONTAP 파일 시스템의 아키텍처 설계 상태에 대한 PDF 보고서를 다운로드할 수 있습니다.link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["NetApp Workload Factory에서 FSx for ONTAP 파일 시스템의 아키텍처 설계 상태를 확인하십시오."]
