= 홈 페이지에는 스토리지에 대한 well-architected 문제 및 EMS 이벤트가 포함되어 있습니다
:allow-uri-read: 




=== 홈 페이지에는 스토리지에 대한 well-architected 문제 및 EMS 이벤트가 포함되어 있습니다

NetApp Workload Factory 홈 페이지에는 워크로드에 대한 아키텍처 문제 및 FSx for ONTAP 비상 관리 시스템(EMS) 이벤트가 표시되는 포커스 타일이 있습니다. 여기에서 스토리지 워크로드로 이동하여 스토리지 환경의 모든 FSx for ONTAP 파일 시스템에 대한 아키텍처 상태 또는 이벤트를 확인할 수 있습니다.



=== S3 액세스 포인트를 사용한 온프레미스 데이터 복제 지원

Workload Factory는 온프레미스 ONTAP 데이터를 클라우드로 복제하여 AWS GenAI, ML 및 분석 기능과 통합하는 것을 지원합니다. S3 액세스 포인트를 사용하여 온프레미스 데이터를 NFS 또는 SMB/CIFS 볼륨으로 복제할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["S3 액세스 포인트를 사용하여 온프레미스 데이터 복제"]



=== Storage의 S3 액세스 포인트 개선 사항

Storage workload for NetApp Workload Factory에서 S3 액세스 포인트 관리 기능이 여러 가지로 개선되었습니다. S3 액세스 포인트에 대한 네트워크 구성 세부 정보를 입력하고 S3 액세스 포인트 태그를 추가할 수 있습니다. 또한 S3 버킷 세부 정보를 확인하고 S3 액세스 포인트 관리를 위한 다양한 작업을 수행할 수 있습니다.



==== Storage에서 사용 가능한 S3 버킷 세부 정보

S3 액세스 포인트에 메타데이터가 활성화되면 NetApp Workload Factory는 AWS S3 버킷을 자동으로 스캔하고 S3 테이블을 채워 모든 객체, 해당 메타데이터, 속성 및 태그에 대한 명확한 스냅샷을 제공합니다. 이러한 세부 정보에 액세스하면 관리 중인 데이터에 대한 제어, 가시성 및 신뢰성을 유지하는 동시에 운영 오버헤드를 줄일 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["FSx for ONTAP 파일 시스템의 S3 액세스 포인트에 대한 세부 정보를 확인하세요"]



==== S3 액세스 포인트에 대한 추가 관리 작업

NetApp Workload Factory는 S3 액세스 포인트에 대한 추가 관리 작업을 제공합니다. NetApp Workload Factory 인터페이스에서 액세스 포인트 세부 정보를 확인하고, 기존 S3 액세스 포인트를 수정하고, S3 액세스 포인트 태그를 추가 또는 제거할 수 있어 객체 스토리지 관리 작업을 간소화할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["NetApp Workload Factory에서 S3 액세스 포인트 관리"]



=== 잘 설계된 분석 업데이트

Workload Factory는 다음 구성에 대해 FSx for ONTAP 파일 시스템을 분석합니다.

* 캐시 볼륨 크기 최적화: 캐시 볼륨에서 볼륨 autosize 및 scrubbing이 활성화되어 있는지 확인하여 최적의 크기를 유지하고 캐시가 핫 데이터에 집중하여 최고 효율성을 달성합니다.
* 비활성 블록 디바이스: 블록 디바이스가 7일 연속 사용되지 않은 경우 블록 디바이스 데이터를 아카이빙하거나 블록 디바이스를 삭제하는 것이 좋습니다.
* 스토리지 VM 논리적 보고: 스토리지 VM의 기본 보고 설정이 논리적으로 설정되어 있는지 확인하여 볼륨 수준에서 스토리지 사용량을 더 잘 파악할 수 있도록 합니다.




=== 블록 디바이스용 추가 카드

스토리지 워크로드의 블록 디바이스 탭에 블록 디바이스 사용량 및 보호 상태에 대한 빠른 인사이트를 제공하는 세 가지 새로운 카드가 추가되었습니다.

* 스토리지 효율성: 사용된 스토리지 용량과 사용 가능한 스토리지 용량을 표시하며, 사용된 용량은 SSD 및 용량 풀 스토리지 계층별로 구분됩니다.
* 보호 장치: 스냅샷, 원격 복제, NetApp 자율형 랜섬웨어 보호(ARP/AI) 및 백업이 적용된 블록 장치의 비율을 표시합니다.
* 사용되지 않는 장치: 블록 장치 중 7일 연속 사용되지 않은 장치가 있는지 표시하여 사용되지 않는 리소스를 효과적으로 식별하고 관리할 수 있도록 도와줍니다. 여기에서 link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html#archive-the-data-of-an-inactive-block-device["사용하지 않는 블록 디바이스의 공간 확보"]을(를) 수행할 수 있습니다.




=== 이니시에이터 그룹 생성 및 관리 지원

NetApp Workload Factory는 FSx for ONTAP 파일 시스템의 블록 스토리지용 이니시에이터 그룹(igroup) 생성 및 관리를 지원합니다. 이니시에이터 그룹은 블록 장치(LUN)를 해당 장치에 액세스할 수 있는 컴퓨팅 리소스에 연결하여 SAN 환경에서 블록 스토리지에 대한 권한 계층을 제공합니다.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-igroup.html["NetApp Workload Factory에서 이니시에이터 그룹 생성"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-igroups.html["NetApp Workload Factory에서 기존 이니시에이터 그룹을 관리합니다"]

