= 잘 설계된 분석 업데이트
:allow-uri-read: 




=== 잘 설계된 분석 업데이트

Workload Factory는 FSx for ONTAP 파일 시스템에서 *비활성 NAS 볼륨*을 분석합니다. 구성 분석을 통해 활발하게 사용되지 않는 NAS 볼륨을 식별하고 스토리지 활용도를 최적화하고 비용을 절감하기 위한 권장 사항을 제시합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["잘 설계된 FSx for ONTAP 파일 시스템 구현"]



=== S3 액세스 포인트용 저널 테이블 기능

저널 테이블 기능은 FSx ONTAP S3 객체 스토리지를 대규모로 관리할 수 있는 방법을 제공하여 버킷의 객체에 대한 사용자 액세스 이벤트 및 작업을 쉽게 감사할 수 있도록 합니다. Workload Factory를 사용하면 버킷과 S3 테이블에 대한 자동 스캔을 설정하여 모든 객체, 객체 세부 정보 및 사용자 작업을 표시하는 이벤트 기록을 유지할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/setup-journal-table.html["NetApp Workload Factory용 저널 테이블 인프라를 설정합니다"]



=== 기존 igroup 관리 지원

Workload Factory는 기존 igroup 관리를 지원합니다. 블록 디바이스와 호스트 이니시에이터를 추가하거나 제거하여 배포된 워크로드를 정시에 제공할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["NetApp Workload Factory에서 블록 스토리지를 관리합니다"]



=== FlexVol 볼륨에 대한 애그리게이트 지정 지원

Workload Factory는 선택한 애그리게이트에 FlexVol 볼륨을 생성하는 기능을 지원합니다. 이를 통해 모든 파일 시스템 리소스에 용량 및 성능 로드를 분산할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["NetApp Workload Factory에서 FlexVol 볼륨 생성"]
