= 모든 FSx for ONTAP 시스템에서 사용할 수 있는 새로운 잘 설계된 대시보드
:allow-uri-read: 




[[new-well-architected-dashboard-available-for-all-fsx-for-ontap-systems]]
=== 모든 FSx for ONTAP 시스템에서 사용할 수 있는 새로운 잘 설계된 대시보드

잘 설계된 분석 기능은 이제 NetApp Workload Factory의 새로운 잘 설계된 대시보드에서 FSx for ONTAP 파일 시스템에 대해 사용할 수 있습니다. 새로운 대시보드는 모든 계정 및 지역의 파일 시스템과 해당 구성을 한 곳에서 중앙 집중식으로 보여줍니다. 파일 시스템에서 *잘 설계된* 탭을 방문하면 팝업 알림이 표시됩니다. Workload Factory의 왼쪽 탐색 메뉴에서 *잘 설계된*을 선택하여 새 대시보드에 액세스하십시오.

특정 파일 시스템에 대한 잘 설계된 분석은 스토리지의 *Well-architected* 메뉴 옵션에서 계속 이용할 수 있습니다.



[[volumes-explorer]]
=== 볼륨 탐색기

볼륨 탐색기를 사용하면 NetApp Workload Factory의 모든 볼륨을 간편하게 검색할 수 있습니다. 블록 또는 파일 워크로드를 처리하는 볼륨을 빠르게 확인할 수 있습니다. 각 볼륨의 논리적 크기, 물리적 사용 용량, 스토리지 효율성 기능(압축, 중복 제거, 압축) 사용 여부를 볼 수 있습니다. 이름, 상태(사용 가능/실패), 지연 시간, 크기, 사용 용량 및 보호 기능별로 필터링하고 정렬할 수 있습니다.



[[enhanced-email-notifications-for-replication-delays]]
=== 복제 지연에 대한 향상된 이메일 알림 기능

복제 지연에 대한 이메일 알림에 이제 영향을 받는 관계에 대한 자세한 정보가 포함됩니다. 이 알림을 통해 영향을 받는 관계를 신속하게 파악하고 Workload Factory 콘솔에서 확인할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["복제 지연에 대한 알림 활성화"]



[[block-device-creation-enhancement]]
=== 블록 장치 생성 개선

Workload Factory는 볼륨 스냅샷에서 블록 장치 생성을 지원합니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Workload Factory에서 볼륨 스냅샷으로 블록 장치 생성"]
